version: '3.9'
services:
  db:
    image: postgres:13
    restart: always
    container_name: mpath-dev-database
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: mpa

  db-test:
    image: postgres:13
    restart: always
    container_name: mpath-test-database
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: mpathtest
    volumes:
      - ./test/db:/data
