on:
  push:
    branches:
      - "dev"
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        with:
          version: "7.14.2"
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: 'eu-west-1'

      - name: Build
        run: pnpm run clean && pnpm run build

      - name: Deploy
        env:
          PUBLIC_GOOGLE_OAUTH_CLIENT_ID: 829288200910-2s4jvqauhtpplood8o3hqhhrbqg6e9ug
          PUBLIC_UPLOAD_BASE_URL: /upload/
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.STAGING_GOOGLE_OAUTH_CLIENT_SECRET }}
          LOG_LEVEL: debug
          LOG_DB_QUERIES: false
          LOG_TRANSPORT: lambda
          ORIGIN: https://mpath-dev.freetls.fastly.net/
          FASTLY_SERVICE_ID: ${{ secrets.STAGING_FASTLY_SERVICE_ID }}
          FASTLY_API_KEY: ${{ secrets.STAGING_FASTLY_API_KEY }}
        run: cd stack && cdk deploy --app ./dist/stack.js --require-approval never MPAth-staging

      - name: Update Fastly dictionary
        env:
          FASTLY_SERVICE_ID: ${{ secrets.STAGING_FASTLY_SERVICE_ID }}
          FASTLY_API_KEY: ${{ secrets.STAGING_FASTLY_API_KEY }}
          FASTLY_ROUTING_DICTIONARY_ID: ${{ secrets.STAGING_FASTLY_ROUTING_DICTIONARY_ID }}

        run: pnpm -F "@mpa/scripts" run deploy-fastly-dictionary

      - name: File logging
        if: always()
        run: ls -lRh packages/stack/cdk.out
      - name: Template logging
        if: always()
        run: cat packages/stack/cdk.out/*.json
